//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "nar_info")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub store_path_hash: String,
    pub store_path: String,
    pub nar_hash: String,
    pub nar_size: i64,
    pub cache_url: String,
    pub status: String,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
